### ISSUE TITLE
unable to install local host after running flask

### ISSUE THREAD

**Issue by BaderOtaibi-code** [prosodylab/prosobeast-annotation-tool#2]
[Thanks](url) for your intersting proiject . I followed the instructions to install the tool and run the code as it is shown in the attached images. However, when I reached to run Flask on localhost where I am asked to use the tool simply  by navigating to this address: http://localhost:5000 (i.e. http://127.0.0.1:5000/). Unfortunately,it does not work and it gives me as it is shown in the attachment file.

I am wondering if you could help me in this regard to upload my  files and run the scripts according to your instructions in "README file".

Taking into consideration that I used the machine with the following specifications:
Processor	Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz   2.70 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor (Windows)

Thanks a lot for your time and cooperation.

Regards
Bader

**Comment by gerazov** [comment]
Thanks for liking the project :pray:

In your e-mail you say:

> The issue was about the installation of the entire tool "ProsBeast". Most of prerequests and requirements were installed properly. However, the final step was not executed completely where I should run a flask on a local host server.  I reached to this step:

```
* Serving Flask app "annotation_tool.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
> After that , it took me to the HTML page and some buttons were activated and others were not. It was not a full version. It looks like the attached screenshot.

![Prosobeat tool running_problem-1](https://user-images.githubusercontent.com/15214418/141260557-11bd2fcf-f95d-42c0-ac78-50a2d6c48acf.PNG)

This looks like the tool is up and running (and it is the full version). It won't let you go to the annotation screen because it's necessary to upload the labels as well as the data. Uploading the audio is optional but recommended.

**Comment by gerazov** [comment]
Closing because of lack of information.
